apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: macic-sandbox
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "web-app"
        static_configs:
          - targets: ["web-app:8000"]
