apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: macic-sandbox
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP